export type ModuleStatus = {
  device: string;
  device_wxid?: string;
  device_nickname?: string;
  enabled?: boolean;
  runtime_status?: string;
  pending_outbox?: number;
  leased_outbox?: number;
  sent_outbox?: number;
  failed_outbox?: number;
  last_outbox_id?: number;
  last_outbox_status?: string;
  last_register_at?: string;
  last_poll_at?: string;
  last_ack_at?: string;
  last_poll_limit?: number;
  last_poll_item_count?: number;
  last_ack_sent_count?: number;
  last_ack_failed_count?: number;
  last_outbound_ack_at?: string;
};

export type ApiKey = {
  code: string;
  api_key?: string;
  device?: string;
  nickname?: string;
  enabled?: boolean;
  created_at?: string;
  updated_at?: string;
};

export type ModuleContact = {
  id: number;
  device: string;
  owner_wxid?: string;
  wxid: string;
  nickname?: string;
  remark?: string;
  alias?: string;
  type?: number;
  verify_flag?: number;
  chatroom: boolean;
  deleted: boolean;
  last_seen_at?: string;
  updated_at?: string;
};

export type StoredMessage = {
  id: number;
  source_id?: string;
  event_id?: number;
  chat_record_id?: number;
  device: string;
  chat_id?: string;
  chat_kind?: "direct" | "room" | string;
  owner_wxid?: string;
  direction: "recv" | "sent" | string;
  from_wxid?: string;
  to_wxid?: string;
  room_id?: string;
  sender_wxid?: string;
  text: string;
  message_type: number;
  kind?: string;
  appmsg_type?: number;
  appmsg_subtype?: string;
  appmsg_title?: string;
  appmsg_description?: string;
  appmsg_url?: string;
  appmsg_file_name?: string;
  appmsg_app_name?: string;
  unsupported?: string[];
  evidence?: string[];
  location_latitude?: number;
  location_longitude?: number;
  location_scale?: number;
  location_label?: string;
  location_poiname?: string;
  location_info_url?: string;
  location_poi_id?: string;
  location_from_poi_list?: boolean;
  location_poi_category_tips?: string;
  media_kind?: string;
  media_mime?: string;
  media_name?: string;
  media_url?: string;
  media_size?: number;
  raw_provider?: string;
  create_time?: number;
  created_at?: string;
  chat_name?: string;
  chat_remark?: string;
  chat_alias?: string;
  chat_display_name?: string;
  chat_deleted?: boolean;
};

export type LiveMessageEvent = {
  id?: string;
  event_id?: number;
  chat_record_id?: number;
  device: string;
  chat_id?: string;
  chat_kind?: "direct" | "room" | string;
  direction: "recv" | "sent" | string;
  from?: string;
  to?: string;
  room_id?: string;
  sender?: string;
  text: string;
  message_type?: number;
  kind?: string;
  appmsg_type?: number;
  appmsg_subtype?: string;
  appmsg_title?: string;
  appmsg_description?: string;
  appmsg_url?: string;
  appmsg_file_name?: string;
  appmsg_app_name?: string;
  unsupported?: string[];
  evidence?: string[];
  location_latitude?: number;
  location_longitude?: number;
  location_scale?: number;
  location_label?: string;
  location_poiname?: string;
  location_info_url?: string;
  location_poi_id?: string;
  location_from_poi_list?: boolean;
  location_poi_category_tips?: string;
  media_kind?: string;
  media_mime?: string;
  media_name?: string;
  media_url?: string;
  media_size?: number;
  raw_provider?: string;
  create_time?: number;
  chat_name?: string;
  chat_remark?: string;
  chat_alias?: string;
  chat_display_name?: string;
  chat_deleted?: boolean;
};
